server:
  port: 9093

spring:
  profiles:
    active: dev
  application:
    name: restaurant
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect