server:
  port: 8082
spring:
  profiles:
    active: dev
  application:
    name: catalogue
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
